Add check for parallel

diff --git a/default_extract b/default_extract
--- a/default_extract
+++ b/default_extract
@@ -1,5 +1,6 @@
 #! /usr/bin/env bash
 SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+
 if [ -t 0 ] ; then
     if [ "$#" -ne 1 ]; then
         echo "No STDIN input detected (non-terminal), and no file argument supplied"
@@ -8,6 +9,8 @@ if [ -t 0 ] ; then
     echo "INFO: Reading data from '$1'." 1>&2
     $SCRIPT_DIR/regexp_dotno "$1" | $SCRIPT_DIR/tolower | sort | uniq;
 else
+    command -v parallel >/dev/null 2>&1 || \
+	{ echo >&2 "[INFO] This script requires parallel but it's not installed. Aborting."; exit 1; }
     echo "INFO: Reading data from stdin." 1>&2
     parallel --pipe $SCRIPT_DIR/regexp_dotno | $SCRIPT_DIR/tolower | sort | uniq;
 fi
